#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6468929009                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Outfitopia - Digital Wardrobe                                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your style, streamlined.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : 
your_link                                 : 
your_city                                 : 
email_address                             : help@outfitopia.app
facebook_username                         :           
facebook_link                             : https://bit.ly/3THdi5w                              
instagram_username                        : outfitopia_app
twitter_username                          : outfitopia_app
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Digitize your wardrobe
    description                           : Categorize clothes by color, season, occasion or create your own custom categories.
    fontawesome_icon_name                 : tshirt
    
  - title                                 : Compose outfits
    description                           : Create endless looks that you truly love and build your own style.
    fontawesome_icon_name                 : star

  - title                                 : Check your closet on the go
    description                           : Your entire wardrobe is seamlessly synchronized across multiple devices.
    fontawesome_icon_name                 : cloud



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.2

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#E1C7FF"

link_color                                : "#6234D5"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#747479"

feature_icons_foreground_color            : "#E1C7FF"
feature_icons_background_color            : "#6234D5"

social_icons_foreground_color             : "#E1C7FF"
social_icons_background_color             : "#6234D5"

footer_text_color                         : "#6234D5"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
